### ISSUE TITLE
Can't seem to reproduce ipynb shown in README

### ISSUE THREAD

**Issue by rkabrick** [ahmedkhalf/jupyter-nvim#1]
Hello! 

First: to say I am excited for this plugin would be a significant understatement. I have been looking for something like this and when I saw your post on Reddit I was thrilled! 

Second... I have installed the plugin, and even double-checked it was loaded (via `PackerLoad jupyter-nvim`) but cannot seem to reproduce the state you showcase in the README. Any ideas on how I could do that? I'd love to contribute to this and help in any way I can I just need to get it working as is hahah.

Thanks in advance and really great work so far!

**Comment by ahmedkhalf** [comment]
Hum, this is very strange, allow me to test using a fresh nvim config.

**Comment by ahmedkhalf** [comment]
I am indeed experiencing the same issue. @rkabrick Please run `:UpdateRemotePlugins` and let me know the output as well as if it fixes your issue on restart.

**Comment by rkabrick** [comment]
So the output is just "Generated manifest... ~/.local/share/nvim/rplugin.vim". And when I check what's in the file it's blank.

<img width="363" alt="CleanShot 2021-06-13 at 12 13 45" src="https://user-images.githubusercontent.com/31963805/121814772-d21cad00-cc40-11eb-8f86-824398c21eb1.png">

**Comment by ahmedkhalf** [comment]
Hum, perhaps it's a dependency problem? Did you try installing nbformat:
https://pypi.org/project/nbformat/ ? And running UpdateRemotePlugins

**Comment by rkabrick** [comment]
Yup, still no luck :/

**Comment by ahmedkhalf** [comment]
Wow this is extremely weird, I tried downloading the plugin on another machine but everything was smooth. Okay final try here:

run `:checkhealth` and tell me if you have any warnings and errors regarding the python3 provider and try to fix them if possible.

After there are no problems, restart, make sure the plugin is installed and loaded and then :UpdateRemotePlugins wait a bit then restart again and let me know if the plugin works. 

Also you are running nvim 5.0 right?

**Comment by rkabrick** [comment]
Long time no see! hahaha.. I apologize for the huge gap in my response... work has been crazy. 

In any event, I believe I am much closer to getting this working. The error I have now is that when I open an ipynb file, I get the JSON code with no rendering of the Jupyter nvim UI. Additionally, if I open a blank ipynb file, I get no python syntax, and the filetype is picked up as json

**Comment by ahmedkhalf** [comment]
Did you call updateremoteplugins? They were some additions since last
update, so some things changed.

**Comment by rkabrick** [comment]
Yes I did and that did change something... perhaps the error I get when opening an example ipynb file will shed some light on possible issues

```
Loading...

error caught while executing async callback:
NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")
Traceback (most recent call last):
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/brick/.local/share/lunarvim/site/pack/packer/start/jupyter-nvim/rplugin/python3/jupyter-nvim/__init__.py", line 45, in write_notebook
    nb = self.notebook_manager.add_notebook(bufnr, filename)
  File "/Users/brick/.local/share/lunarvim/site/pack/packer/start/jupyter-nvim/rplugin/python3/jupyter-nvim/utils.py", line 56, in add_notebook
    nb = Notebook(filename, bufnr, self._nvim, self._lua_bridge)
  File "/Users/brick/.local/share/lunarvim/site/pack/packer/start/jupyter-nvim/rplugin/python3/jupyter-nvim/utils.py", line 8, in __init__
    self._nb = nbformat.read(filename, as_version=4)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/nbformat/__init__.py", line 141, in read
    return reads(f.read(), as_version, **kwargs)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/nbformat/__init__.py", line 73, in reads
    nb = reader.reads(s, **kwargs)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/nbformat/reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...") from e
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '\n\n\n\n\n\n<!DOCTYPE html>\n<html lang...

the call was requested at
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/pynvim/plugin/host.py", line 124, in _on_request
    rv = handler(*args)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/pynvim/plugin/host.py", line 92, in _wrap_delayed_function
    self._request_handlers[name](*args)
  File "/Users/brick/.local/share/virtualenvs/error-correcting-0fIemReO/lib/python3.9/site-packages/pynvim/plugin/host.py", line 102, in _wrap_function
    return fn(*args)
  File "/Users/brick/.local/share/lunarvim/site/pack/packer/start/jupyter-nvim/rplugin/python3/jupyter-nvim/__init__.py", line 48, in openNotebook
    self.nvim.async_call(write_notebook)
```

**Comment by rkabrick** [comment]
Alright so I'm 99% sure it was an issue between virtualenv tools (pyenv & pipenv)... Now I have the Run Code and Delete Cell (HAZAHH)

But... everything is monochromatic (no python highlighting) and I get an issue (end of file expected)
